"""Campaign table created

Revision ID: d37fae67729c
Revises: 
Create Date: 2025-12-14 14:45:01.608884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37fae67729c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('daily_budget', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('ad_headline', sa.String(length=255), nullable=False),
    sa.Column('ad_description', sa.Text(), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=False),
    sa.Column('asset_url', sa.String(length=2048), nullable=True),
    sa.Column('google_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
